# Generated by Django 5.1.3 on 2025-01-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
    ]
