# Generated by Django 5.1.3 on 2025-01-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_imagen_platillo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='imagen',
        ),
    ]
